server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }

    # Route API calls to the internal Kubernetes Service
    location /api/ {
        proxy_pass http://backend-svc.default.svc.cluster.local:5000/api/;
    }
}